export const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const DAY_NAMES_SHORT = [
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
];

export const appContextInitialData = {
  blocks: [],
  allUniqueTags: [],
  stats: {
    totalBlocks: 0,
    ongoingBlocks: 0,
    totalBlockedHours: 0,
    longestBlock: 0,
  },
  isModalOpen: false,
  editingBlock: null,
  handleOpenModal: () => {},
  handleCloseModal: () => {},
  handleSaveBlock: () => {},
  handleResolveBlock: () => {},
  handleDeleteBlock: () => {},
  viewingBlock: null,
  handleCloseDetailsModal: () => {},
  handleEditBlock: () => {},
  handleViewBlockDetails: () => {},
  setBlocks: () => {},
};
